# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{paypal-ipn}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David Wilkie"]
  s.date = %q{2010-10-06}
  s.email = %q{dwilkie@gmail.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "MIT-LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "lib/generators/paypal/initializer/USAGE",
     "lib/generators/paypal/initializer/initializer_generator.rb",
     "lib/generators/paypal/initializer/templates/paypal.rb",
     "lib/paypal.rb",
     "lib/paypal/ipn/ipn.rb",
     "lib/paypal/ipn/types/masspay.rb",
     "lib/paypal/ipn/variables/buyer.rb",
     "lib/paypal/ipn/variables/item.rb",
     "lib/paypal/masspay.rb",
     "paypal-ipn.gemspec"
  ]
  s.homepage = %q{http://github.com/dwilkie/paypal}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Another ruby wrapper for Paypal}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, [">= 0.6.1"])
    else
      s.add_dependency(%q<httparty>, [">= 0.6.1"])
    end
  else
    s.add_dependency(%q<httparty>, [">= 0.6.1"])
  end
end

